# Generated by Django 5.0.2 on 2024-02-27 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_title', models.CharField(blank=True, max_length=755, null=True)),
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('dfg_verfahren', models.CharField(blank=True, max_length=455, null=True)),
                ('researchers', models.JSONField(blank=True, max_length=2000, null=True)),
                ('institutions', models.JSONField(blank=True, max_length=2000, null=True)),
                ('antragstellende_mitverantwortliche', models.JSONField(blank=True, max_length=2000, null=True)),
                ('applicant', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'projects',
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('name', models.CharField(blank=True, max_length=400, null=True)),
                ('person_id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(blank=True, max_length=400, null=True)),
                ('current_inst', models.CharField(blank=True, max_length=600, null=True)),
                ('category', models.CharField(blank=True, max_length=400, null=True)),
                ('projects', models.ManyToManyField(blank=True, related_name='people', to='projects.project')),
            ],
            options={
                'verbose_name_plural': 'people',
                'db_table': 'person',
            },
        ),
    ]
